dir: /etc/puppetlabs/puppet/ssl/ca/requests
cmd_sign: /opt/puppetlabs/bin/puppet cert sign %s
logfile: /var/log/autosignr/autosignr.log
accounts_aws:
  - name: My AWS account
    key: YOUR_ACCESS_KEY
    secret: YOUR_SECRET_KEY
    regions:
      - us-west-2
      - us-east-1
  - name: A second AWS account
    key: YOUR_ACCESS_KEY
    secret: YOUR_SECRET_KEY
    regions:
      - us-east-1
